steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
  # deploy container image to GKE
- name: "ubuntu"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i "s#<replace>#$PROJECT_ID#g" gke.yaml
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod